# docker-compose does not work with fly.io, so expect to only ever run the compose file when attempting to run the development or test environment using docker compose
services:
  app_dev:
    env_file: "../packages/backend/.env.development.local"
    depends_on:
      - redis_test
    build:
      context: ..
      dockerfile: ./docker/backend/Dockerfile
      target: backend-dev
    environment:
      REDIS_HOST: "redis_test"
    develop:
      watch:
        - action: sync
          path: ../packages/backend/src
          target: /app/packages/backend/src
    container_name: medrevue-backend-development
    profiles: ["dev", "test"]
    ports:
      - "3000:3000"
  redis_test:
    image: redis:latest
    container_name: "redis_test"
    ports:
      - "6379:6379"
    profiles: ["test"] #NOTE: I didn't use volumes because I think this should only be used for testing
  redis_prod:
    image: redis:latest
    container_name: "redis_test"
    ports:
      - "6379:6379"
    profiles: ["prod"]
    #TODO: add volume for redis
  app_prod:
    env_file: "../packages/backend/.env.production.local"
    depends_on:
      - redis_prod
    build:
      context: ..
      dockerfile: ./docker/backend/Dockerfile
      target: fullstack-prod
    environment:
      REDIS_HOST: "redis_prod"
    container_name: medrevue-production
    profiles: ["prod"]
    ports:
      - "3000:3000"
