# docker-compose does not work with fly.io, so expect to only ever run the compose file when attempting to run the development or test environment using docker compose
services:
  app_dev:
    env_file: "../packages/backend/.env.development.local"
    depends_on:
      - redis_test
    build:
      context: ..
      dockerfile: ./docker/backend/Dockerfile
    environment:
      REDIS_HOST: "redis_test"
    develop:
      watch:
        - action: sync
          path: ./src
          target: ./src
    container_name: medrevue-backend-development

    profiles: ["dev", "test"]
    ports:
      - "3000:3000"
  redis_test:
    image: redis:latest
    container_name: "redis_test"
    ports:
      - "6379:6379"
    profiles: ["test"]
